config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  devise_for :users
  resources :users, only: %i[show]
  resources :events
  resources :enrollments, only: %i[new create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User", foreign_key: "user_id"
  has_many :enrollments
  has_many :attendees, through: :enrollments, source: :user

  scope :in_the_past, -> { where('date < ?', Time.now) }
  scope :in_the_future, -> { where('date >= ?', Time.now) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :enrollments
  has_many :events, inverse_of: :creator
  has_many :attended_events, through: :enrollments, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password)}

      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :current_password)}
    end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!, only: %i[create new destroy]

  def new
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.find(params[:id])
    @event.attendees << current_user
    flash[:notice] = 'You have registered for the event'
    redirect_to root_path
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.attendees.destroy(current_user)
      flash[:success] = "You are no longer attending this event"
    else
      flash[:error] = "Something went wrong"
    end
    redirect_to root_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: %i[create new destroy update edit]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      flash[:success] = "Object successfully created"
      redirect_to root_path
    else
      flash[:error] = "Something went wrong"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      flash[:success] = "Object was successfully updated"
      redirect_to root_path
    else
      flash[:error] = "Something went wrong"
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.destroy
      flash[:success] = "Object was successfully updated"
    else
      flash[:error] = "Something went wrong"
    end
    redirect_to root_path
  end
  

  private

  def event_params
    params.require(:event).permit(:title, :description, :date, :location, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user_events = current_user.events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/enrollments/create.html.erb
<h1>Enrollments#create</h1>
<p>Find me in app/views/enrollments/create.html.erb</p>

app/views/enrollments/new.html.erb
<h1>Enrollments#new</h1>
<p>Find me in app/views/enrollments/new.html.erb</p>

app/views/events/create.html.erb
<h1>Event#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/edit.html.erb
<div class="main-container">
  <%= render 'partials/shared/navbar' %>
  <div class="container-fluid center-block">
    <h1>New Event</h1>

    <% if @event.errors.any? %>
      <div id='error_explanation'>
        <h2><% pluralize(@event.errors.count, 'error') %> prohibited this event from being saved:</h2>
        <ul>
        <% @event.error.full_messages.each do |msg| %>
          <li><%= msg %></li>    
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_with model:@event do |f| %>
      <%= f.label 'Title:' %><br>
      <%= f.text_field :title %><br>
      <%= f.label 'Description:' %><br>
      <%= f.text_field :description %><br>
      <%= f.label 'Location:' %><br>
      <%= f.text_field :location %><br>
      <%= f.label 'Date:' %><br>
      <%= f.datetime_field :date %><br>
      <%= f.hidden_field :user_id, value: current_user.id %><br>
      <%= f.submit 'Edit Event' %>
    <% end %>
  </div>  
</div>

app/views/events/index.html.erb
<div class="main-container">
  <%= render 'partials/shared/navbar' %>

  <div class="container-fluid">
    <h1>Events</h1>
    
    <div class="row">
      <h3>Upcoming Events</h3>
      <div class="panel-group cards">
        <%= render 'partials/events/future_events' %>
      </div>
    </div>
    
    <div class="row">
      <h3>Past Events</h3>
      <div class="panel-group cards">
        <%= render 'partials/events/past_events' %>
      </div>
    </div>
    
  </div>
</div>

app/views/events/new.html.erb
<div class="main-container">
  <%= render 'partials/shared/navbar' %>
  <div class="container-fluid center-block">
    <h1>New Event</h1>

    <% if @event.errors.any? %>
      <div id='error_explanation'>
        <h2><% pluralize(@event.errors.count, 'error') %> prohibited this event from being saved:</h2>
        <ul>
        <% @event.error.full_messages.each do |msg| %>
          <li><%= msg %></li>    
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_with model:@event do |f| %>
      <%= f.label 'Title:' %><br>
      <%= f.text_field :title %><br>
      <%= f.label 'Description:' %><br>
      <%= f.text_field :description %><br>
      <%= f.label 'Location:' %><br>
      <%= f.text_field :location %><br>
      <%= f.label 'Date:' %><br>
      <%= f.datetime_field :date %><br>
      <%= f.hidden_field :user_id, value: current_user.id %><br>
      <%= f.submit 'Post Event' %>
    <% end %>
  </div>  
</div>

app/views/events/show.html.erb
<div class="main-container">
<%= render 'partials/shared/navbar' %>
<div>Title: <%= @event.title %></div>
<div>Description: <%= @event.description %></div>
<div>Date: <%= @event.date.strftime('%d/%m/%Y %H:%M') %></div>
<div>Location: <%= @event.location %></div>
<div>Attendees: <%= @event.attendees.count %></div>
<div>Creator: <%= @event.creator.username %></div> 

<% if current_user && @event.creator != current_user && !@event.attendees.include?(current_user) && @event.date > Time.now  %>
  <%= button_to "Attend event", enrollments_path(user_id: current_user.id, id: @event.id), method: :post, class: "btn btn-primary" %>
<% else %>
  <% if current_user == @event.creator %>
    <div>You have created this event</div>
  <% elsif @event.date < Time.now %>
    <div>This event already happened</div>
  <% else %>
    <div>You have registered for the event</div>
  <% end %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/events/_future_events.erb
<% @events.in_the_future.each do |event| %>
  <div class="panel panel-primary text-center" style="width: 24rem;">
    <div class="panel-heading">
      <h5 class="panel-heading panel-title"><%= event.title %></h5>
    </div>
    <div class="panel-body"><%= event.description %></div>
    <ul class="list-group">
      <li class="list-group-item"><%= event.date.strftime('%d/%m/%Y %H:%M') %></li>
      <li class="list-group-item">Location: <%= event.location %></li>
      <li class="list-group-item">Attendees: <%= event.attendees.count %></li>
      <li class="list-group-item">Host: <%= event.creator.username %></li>
    </ul>
    <div class="panel-footer">
    <% if current_user && event.creator != current_user && !event.attendees.include?(current_user) && event.date > Time.now  %>
      <%= button_to "Attend event", enrollments_path(user_id: current_user.id, id: event.id), method: :post, class: "btn btn-primary" %>
    <% elsif current_user == event.creator %>
      <%= link_to "Edit Event", edit_event_path(id: event.id), method: :get, class: "btn btn-primary" %>
      <%= button_to "Delete Event", event_path(event.id), method: :delete, class: "btn btn-danger" %>
    <% else %>
      <%= button_to "Dont Attend", enrollment_path(event.id), method: :delete, class: "btn btn-danger" %>
    <% end %>
    </div>
  </div>
<% end %>

app/views/partials/events/_past_events.erb
<% @events.in_the_past.each do |event| %>
  <div class="panel panel-primary text-center" style="width: 24rem;">
    <div class="panel-heading">
      <h5 class="panel-heading panel-title"><%= event.title %></h5>
    </div>
    <div class="panel-body"><%= event.description %></div>
    <ul class="list-group">
      <li class="list-group-item"><%= event.date.strftime('%d/%m/%Y %H:%M') %></li>
      <li class="list-group-item">Location: <%= event.location %></li>
      <li class="list-group-item">Attendees: <%= event.attendees.count %></li>
      <li class="list-group-item">Host: <%= event.creator.username %></li>
    </ul>
    <div class="panel-footer">
    <% if current_user && event.creator != current_user && !event.attendees.include?(current_user) && event.date > Time.now  %>
    <%= button_to "Attend event", enrollments_path(user_id: current_user.id, id: event.id), method: :post, class: "btn btn-primary" %>
    <% elsif current_user == event.creator %>
      <%= link_to "Edit Event", edit_event_path(id: event.id), method: :get, class: "btn btn-primary" %>
      <%= button_to "Delete Event", event_path(event.id), method: :delete, class: "btn btn-danger" %>
    <% else %>
      <%= button_to "Attend event", enrollments_path, class: "btn btn-primary disabled" %>
    <% end %>
    </div>
  </div>
<% end %>

app/views/partials/shared/_navbar.erb
<nav class="navbar navbar-dark bg-dark navbar-static-top" style="background-color: #212529">
    <div class="navbar-inner">
      <%= link_to "Private Event", root_path, class: 'navbar-brand', style: 'color: white' %>
      <ul class="nav pull-right nav-inline-group">
          <%= link_to "New Event", new_event_path, class: 'btn btn-primary btn-sm navbar-btn' %>
          <% if user_signed_in? %>
            <%= link_to "My Profile", user_path(current_user.id), class: 'btn btn-primary btn-sm navbar-btn' %>
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm navbar-btn' %>
          <% else %>
              <%= button_to "Log In", new_user_session_path, method: :get, class: 'btn btn-primary btn-sm navbar-btn' %>
          <% end %>
      </ul>
    </div>
  </nav>

app/views/partials/users/_attendee_past_events.erb
<% current_user.attended_events.in_the_past.each do |event| %>
  <div class="panel panel-primary text-center" style="width: 24rem;">
    <div class="panel-heading">
      <h5 class="panel-heading panel-title"><%= event.title %></h5>
    </div>
    <div class="panel-body"><%= event.description %></div>
    <ul class="list-group">
      <li class="list-group-item"><%= event.date.strftime('%d/%m/%Y %H:%M') %></li>
      <li class="list-group-item">Location: <%= event.location %></li>
      <li class="list-group-item">Attendees: <%= event.attendees.count %></li>
    </ul>
    <div class="panel-footer">
    <%# <%= button_to "Show event", event_path(id: event.id), method: :get, class: "btn btn-primary" %> 

    <% if current_user && event.creator != current_user && !event.attendees.include?(current_user) && event.date > Time.now  %>
      <%= button_to "Attend event", enrollments_path(user_id: current_user.id, id: event.id), method: :post, class: "btn btn-primary" %>
    <% elsif current_user == event.creator %>
      <%= link_to "Edit Event", edit_event_path(id: event.id), method: :get, class: "btn btn-primary" %>
      <%= button_to "Delete Event", event_path(event.id), method: :delete, class: "btn btn-danger" %>
    <% else %>
      <%= button_to "Attend event", enrollments_path, class: "btn btn-primary disabled" %>
    <% end %>
    </div>
  </div>
<% end %>

app/views/partials/users/_attendee_upcoming_events.erb
<% current_user.attended_events.in_the_future.each do |event| %>
  <div class="panel panel-primary text-center" style="width: 24rem;">
    <div class="panel-heading">
      <h5 class="panel-heading panel-title"><%= event.title %></h5>
    </div>
    <div class="panel-body"><%= event.description %></div>
    <ul class="list-group">
      <li class="list-group-item"><%= event.date.strftime('%d/%m/%Y %H:%M') %></li>
      <li class="list-group-item">Location: <%= event.location %></li>
      <li class="list-group-item">Attendees: <%= event.attendees.count %></li>
    </ul>
    <div class="panel-footer">
    <%# <%= button_to "Show event", event_path(id: event.id), method: :get, class: "btn btn-primary" %> 

    <% if current_user && event.creator != current_user && !event.attendees.include?(current_user) && event.date > Time.now  %>
      <%= button_to "Attend event", enrollments_path(user_id: current_user.id, id: event.id), method: :post, class: "btn btn-primary" %>
    <% elsif current_user == event.creator %>
      <%= link_to "Edit Event", edit_event_path(id: event.id), method: :get, class: "btn btn-primary" %>
      <%= button_to "Delete Event", event_path(event.id), method: :delete, class: "btn btn-danger" %>
    <% else %>
      <%= button_to "Attend event", enrollments_path, class: "btn btn-primary disabled" %>
    <% end %>
    </div>
  </div>
<% end %>

app/views/partials/users/_events_created.erb
<% current_user.events.each do |event| %>
  <div class="panel panel-primary text-center" style="width: 24rem;">
    <div class="panel-heading">
      <h5 class="panel-heading panel-title"><%= event.title %></h5>
    </div>
    <div class="panel-body"><%= event.description %></div>
    <ul class="list-group">
      <li class="list-group-item"><%= event.date.strftime('%d/%m/%Y %H:%M') %></li>
      <li class="list-group-item">Location: <%= event.location %></li>
      <li class="list-group-item">Attendees: <%= event.attendees.count %></li>
    </ul>
    <div class="panel-footer">
    <%# <%= button_to "Show event", event_path(id: event.id), method: :get, class: "btn btn-primary" %> 

    <% if current_user && event.creator != current_user && !event.attendees.include?(current_user) && event.date > Time.now  %>
      <%= button_to "Attend event", enrollments_path(user_id: current_user.id, id: event.id), method: :post, class: "btn btn-primary" %>
    <% elsif current_user == event.creator %>
      <%= link_to "Edit Event", edit_event_path(id: event.id), method: :get, class: "btn btn-primary" %>
      <%= button_to "Delete Event", event_path(event.id), method: :delete, class: "btn btn-danger" %>
    <% else %>
      <%= button_to "Attend event", enrollments_path, class: "btn btn-primary disabled" %>
    <% end %>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="main-container">
  <%= render 'partials/shared/navbar' %>

  <div class="container-fluid">
  <h1>My Profile</h1>
  
  <h2>Hosted:</h2>

  <div class="row">
    <div class="panel-group cards">
      <%= render 'partials/users/events_created' %>
    </div>

  <h2>Attended:</h2>

  <div class="row">
    <h3 class="text-center">Upcoming</h3>
    <div class="panel-group cards">
      <%= render 'partials/users/attendee_upcoming_events' %>
    </div>
    
  <div class="row">
    <h3 class="text-center">Past</h3>
      <div class="panel-group cards">
      <%= render 'partials/users/attendee_past_events' %>
      </div>
    </div>
  </div>
</div>